/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 a.glb 
Author: TheSitthikorn (https://sketchfab.com/TheSitthikorn)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/agent-jonesy-4f58c52acca141e6950575c5f95bd193
Title: Agent Jonesy
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function A(props) {
  const { scene } = useGLTF('/a.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.M_Med_Assassin_Suit} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.M_Med_Soldier_Head} skeleton={nodes.Object_8.skeleton} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.M_SML_Survivor_Hair_02} skeleton={nodes.Object_9.skeleton} />
    </group>
  )
}

useGLTF.preload('/a.glb')
