/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 s.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function S(props) {
  const { nodes, materials } = useGLTF('/s.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.eye__L001.geometry} material={nodes.eye__L001.material} position={[-0.028, 1.599, 0.139]} />
      <mesh geometry={nodes.eye_R001.geometry} material={nodes.eye_R001.material} position={[0.028, 1.599, 0.139]} />
      <mesh geometry={nodes.eyebrow001.geometry} material={nodes.eyebrow001.material} />
      <mesh geometry={nodes.FBHead001.geometry} material={nodes.FBHead001.material} position={[0, 1.557, 0.109]} scale={0.115} />
      <mesh geometry={nodes.male_elegant_suit006.geometry} material={nodes.male_elegant_suit006.material} />
      <mesh geometry={nodes.male_elegant_suit007.geometry} material={nodes.male_elegant_suit007.material} />
      <mesh geometry={nodes.male_elegant_suit008.geometry} material={nodes.male_elegant_suit008.material} position={[0, 1.41, 0.104]} rotation={[-0.378, -0.081, 0]} scale={0.46} />
      <mesh geometry={nodes.male_elegant_suit009.geometry} material={nodes.male_elegant_suit009.material} />
      <mesh geometry={nodes.man_with_suit002.geometry} material={nodes.man_with_suit002.material} />
      <mesh geometry={nodes.mouth_lower_teath001.geometry} material={materials.mouth} position={[0.003, 1.55, 0.076]} />
      <mesh geometry={nodes.mouth_uper_teath001.geometry} material={nodes.mouth_uper_teath001.material} position={[0.003, 1.55, 0.076]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-0.001, 1.304, 0.134]} rotation={[1.26, 0, 0]} scale={[-0.054, -0.13, -0.13]} />
      <mesh geometry={nodes.shoes_oxford_male001.geometry} material={nodes.shoes_oxford_male001.material} />
      <mesh geometry={nodes.tongue001.geometry} material={materials.tongue} position={[0, 0, 0.015]} />
    </group>
  )
}

useGLTF.preload('/s.glb')
