/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 E.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function E(props) {
  const { nodes, materials } = useGLTF('/E.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FBHead001.geometry} material={materials['FBHead.002_preview_mat.1001']} position={[0, 1.557, 0.109]} scale={0.115} />
      <mesh geometry={nodes.FBHead002.geometry} material={materials['FBHead.002_preview_mat.1001']} position={[0, 1.557, 0.109]} scale={0.115} />
      <mesh geometry={nodes.FBHead003.geometry} material={materials['FBHead.002_preview_mat.1001']} position={[0, 1.566, 0.109]} scale={0.115} />
      <mesh geometry={nodes.LCm_008.geometry} material={materials.Hand} position={[0.043, 1.005, 0.083]} rotation={[0, -0.391, Math.PI]} scale={0.074} />
      <mesh geometry={nodes.LCm_008001.geometry} material={nodes.LCm_008001.material} position={[0.129, 1.008, 0.12]} rotation={[0, -0.033, Math.PI]} scale={[0.041, 0.074, 0.052]} />
      <mesh geometry={nodes.Shirt.geometry} material={nodes.Shirt.material} position={[0, 0.282, 0.016]} rotation={[Math.PI / 2, 0, 0]} scale={0.056} />
      <mesh geometry={nodes.eye_R001.geometry} material={materials['FBHead.002_preview_mat.1001']} position={[0.028, 1.599, 0.139]} rotation={[0, 0.052, 0]} />
      <mesh geometry={nodes.eye__L001.geometry} material={materials['FBHead.002_preview_mat.1001']} position={[-0.028, 1.599, 0.139]} rotation={[0, -0.009, 0]} />
      <mesh geometry={nodes.hair002.geometry} material={materials['hair.002']} position={[0, 1.685, 0.051]} rotation={[-0.157, 0.008, -0.031]} scale={0.837} />
      <mesh geometry={nodes.male_elegant_suit006.geometry} material={materials.Suit} />
      <mesh geometry={nodes.male_elegant_suit009.geometry} material={materials.Suit} />
      <mesh geometry={nodes.male_elegant_suit010.geometry} material={materials.Suit} position={[-0.003, 1.372, 0.113]} rotation={[-0.378, -0.081, 0]} scale={0.46} />
      <mesh geometry={nodes.man_with_suit002.geometry} material={materials.Hand} />
      <mesh geometry={nodes.mouth_lower_teath001.geometry} material={nodes.mouth_lower_teath001.material} position={[0.003, 1.55, 0.076]} />
      <mesh geometry={nodes.mouth_uper_teath001.geometry} material={nodes.mouth_uper_teath001.material} position={[0.003, 1.55, 0.076]} />
      <mesh geometry={nodes.shoes_oxford_male001.geometry} material={materials.Suit} />
      <mesh geometry={nodes.tongue001.geometry} material={nodes.tongue001.material} position={[0, 0, 0.015]} />
    </group>
  )
}

useGLTF.preload('/E.glb')
